name: dot-net

on:
  push:
    branches:
      - dot-net
    tags:
      - '*'

  workflow_dispatch:

concurrency:
  group: dot-net-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-libs:
    name: dot-net for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2

      # - name: Setup .NET Core 3.1
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.x

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Check dotnet
        run: dotnet --info

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install Python dependencies
        shell: bash
        run: |
          python3 -m pip install --upgrade pip jinja2

      - name: build nuget packages
        shell: bash
        run: |
          cd scripts/
          # dotnet workload install wasm-tools-net7
          dotnet workload install ios

          ./run.sh
          ls -lh packages

      - uses: actions/upload-artifact@v2
        name: upload nuget packages
        with:
          name: nuget-packages
          path: scripts/packages/*.nupkg

      - name: publish .Net packages to nuget.org
        if: github.repository == 'csukuangfj/PortAudioSharp2'
        shell: bash
        env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          # API_KEY is valid until 2024.07.01
          cd scripts/packages
          dotnet nuget push ./*.nupkg --skip-duplicate --api-key $API_KEY --source https://api.nuget.org/v3/index.json
